name: tictoc
description: Dart network time protocol package by beyo
repository: https://github.com/Beyo-Inc/tictoc
issue_tracker: https://github.com/Beyo-Inc/tictoc/issues
version: 0.0.1

environment:
  sdk: ^3.3.0

dev_dependencies:
  test: ^1.24.0
