name: tictoc
description: Dart network time protocol package by beyo
repository: https://github.com/Beyo-Inc/tictoc
issue_tracker: https://github.com/Beyo-Inc/tictoc/issues
version: 0.1.0

environment:
  sdk: ^3.3.0

dependencies:
  easy_network_time: ^1.0.3
  freezed_annotation: ^2.4.4
  ntp: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  test: ^1.24.0
